FROM python:3.12-slim

WORKDIR /app

# Chromium과 ChromeDriver 설치
RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/*

# Python 패키지 설치
COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

# 프로젝트 전체 복사
COPY . /app

# Vercel Container 기본 HTTP 포트
ENV PORT=80

EXPOSE 80

# Flask 실행
CMD ["/usr/local/bin/gunicorn", "app:app", "--bind", "0.0.0.0:80"]